# Generated by Django 2.1.2 on 2020-04-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=250)),
                ('subheading', models.TextField()),
                ('button', models.CharField(max_length=50)),
                ('image_900x650', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(max_length=200)),
                ('image_one_1000x700', models.ImageField(upload_to='images/')),
                ('image_two_500x730', models.ImageField(upload_to='images/')),
                ('subheading', models.TextField()),
                ('our_approch_heading', models.CharField(max_length=200)),
                ('our_approch_subheading', models.CharField(max_length=200)),
                ('our_mission_heading', models.CharField(max_length=200)),
                ('our_mission_subheading', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('subheading', models.TextField()),
            ],
        ),
    ]
