# Generated by Django 2.1.2 on 2020-04-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_projectsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_description_heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_description_subheading',
            field=models.TextField(null=True),
        ),
    ]
